import { Content } from '@backstage/core-components';
import { useEntity } from '@backstage/plugin-catalog-react';
import { Box, Grid, Paper, Typography } from '@material-ui/core';

export const TrivyReportTab = () => {
  const { entity } = useEntity();
  
  // Get the Trivy report URL from the entity annotation
  const trivyReportUrl = entity.metadata.annotations?.['trivy.security-report'];
  
  if (!trivyReportUrl) {
    return (
      <Content>
        <Grid container spacing={3}>
          <Grid item xs={12}>
            <Paper style={{ padding: '24px' }}>
              <Typography variant="h4" gutterBottom>
                Trivy Report
              </Typography>
              <Typography variant="body1" color="textSecondary">
                No Trivy security report configured for this entity.
              </Typography>
              <Typography variant="body2" color="textSecondary" style={{ marginTop: '16px' }}>
                To enable Trivy reports, add the annotation{' '}
                <code>trivy.security-report: [URL]</code> to your component.
              </Typography>
            </Paper>
          </Grid>
        </Grid>
      </Content>
    );
  }

  return (
    <Content>
      <Grid container spacing={3}>
        <Grid item xs={12}>
          <Paper style={{ padding: '24px' }}>
            <Typography variant="h4" gutterBottom>
              Trivy Security Report
            </Typography>
            <Typography variant="body1" color="textSecondary" paragraph>
              Security vulnerability and compliance analysis for {entity.metadata.name}
            </Typography>
            
            <Box style={{ marginTop: '24px' }}>
              <div style={{ 
                height: '800px', 
                width: '100%', 
                border: '1px solid #e0e0e0',
                borderRadius: '4px',
                overflow: 'hidden'
              }}>
                <iframe
                  src={trivyReportUrl}
                  style={{
                    width: '100%',
                    height: '100%',
                    border: 'none',
                  }}
                  title="Trivy Security Report"
                  sandbox="allow-same-origin allow-scripts allow-forms"
                />
              </div>
            </Box>
            
            <Box style={{ marginTop: '16px' }}>
              <Typography variant="body2" color="textSecondary">
                This report is generated by Trivy and shows security vulnerabilities, 
                compliance issues, and other security-related findings in the codebase.
              </Typography>
              <Typography variant="body2" color="textSecondary" style={{ marginTop: '8px' }}>
                Source: <a href={trivyReportUrl} target="_blank" rel="noopener noreferrer">{trivyReportUrl}</a>
              </Typography>
            </Box>
          </Paper>
        </Grid>
      </Grid>
    </Content>
  );
}; 