apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4Site
  description: AI Platform project is a made to help deliver complex data projects in a quick, secure and standardised way while being compliant with Sodexo policies in terms of security and infrastructure.
  links:
    - url: https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_4site/_workitems/recentlyupdated/
      title: Azure DevOps Board
spec:
  type: usecase
  profile:
    displayName: 4Site
  lifecycle: experimental
  owner: 4site-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IST.GLB.GLB.DataFactory_4site.DataIntegrationPipeline
  description: Description of the data integration pipeline for 4Site
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_4site/_git/IST.GLB.GLB.DataFactory_4site.DataIntegrationPipeline
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: IST.GLB.GLB.DataFactory_4site/IST.GLB.GLB.DataFactory_4site.DataIntegrationPipeline
  links:
    - url: https://aip.datalab.sodexo.com/4-site/docs/4site-integration
      title: 4Site Integration documentation
spec:
  type: repo
  owner: 4site-team
  subcomponentOf: 4Site
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IST.GLB.GLB.DataFactory_4site.DataPublication
  description: Description of the data publication for 4Site
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_4site/_git/IST.GLB.GLB.DataFactory_4site.DataPublication
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: IST.GLB.GLB.DataFactory_4site/IST.GLB.GLB.DataFactory_4site.DataPublication
  links:
    - url: https://aip.datalab.sodexo.com/4-site/docs/4site
      title: 4Site documentation
spec:
  type: repo
  owner: 4site-team
  subcomponentOf: 4Site
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IST.GLB.GLB.Datafactory_4site.CorePipeline
  description: Description of the Core Pipeline repository for 4Site
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_4site/_git/IST.GLB.GLB.Datafactory_4site.CorePipeline
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: IST.GLB.GLB.DataFactory_4site/IST.GLB.GLB.Datafactory_4site.CorePipeline
spec:
  type: repo
  owner: 4site-team
  subcomponentOf: 4Site
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DEV_FSI
  description: Component dedicated to the 4Site DEV Azure environment.
  resource_group:
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG01
      title: GLB-GLB-IENO-AIPEAFSI-DEV-RG01
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG03
      title: GLB-GLB-IENO-AIPEAFSI-DEV-RG03
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSIDEVOPS-DEV-RG01
      title: GLB-GLB-IENO-AIPEAFSIDEVOPS-DEV-RG01
  spn: 
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG01
      title: GLB-DataFactory-4Site-EndUsersManagement-eu-DEV
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG01
      title: GLB-DATALAB.AZU-AIP. 4SiteGDP.eu-DEV
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG01
      title: GLB-DATALAB.AZU-AIP.DevOpsfsi.eu-DEV
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG01
      title: GLB-DATALAB.AZU-AIP.DMYwebappauth.eu-DEV
    - url: https://portal.azure.com/#resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAFSI-DEV-RG01
      title: GLB-DATALAB.AZU-AIP.expareafsi.eu-DEV
  ad_group:
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/69b2cce2-c126-4f71-bf72-f1b4fc492a5c
      title: SG.CE.FR-AIP_FSI_FR_EXP_DEV
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/65c0317b-b47c-400b-a999-00c6d3e99b8e
      title: SG.CE.GLB.EU.4SITE.CTB.DEV
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/9cbdb2b5-4c0b-4d14-a175-215ced635c2f
      title: SG.CE.GLB-ADLS.DEV.EU.4SITE.ADMIN
spec:
  type: infra-environment
  profile:
    displayName: DEV_FSI
  lifecycle: experimental
  subcomponentOf: 4Site
  owner: 4site-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: UAT_FSI
  description: Component dedicated to the 4Site UAT Azure environment.
  resource_group:
    - url: https://portal.azure.com/#resource/subscriptions/daf86ec1-725c-493f-bf09-a1f129b8588a/resourceGroups/GLB-GLB-IENO-AIPEAFSI-UAT-RG01
      title: GLB-GLB-IENO-AIPEAFSI-UAT-RG01
    - url: https://portal.azure.com/#resource/subscriptions/daf86ec1-725c-493f-bf09-a1f129b8588a/resourceGroups/GLB-GLB-IENO-AIPEAFSI-UAT-RG03
      title: GLB-GLB-IENO-AIPEAFSI-UAT-RG03
    - url: https://portal.azure.com/#resource/subscriptions/daf86ec1-725c-493f-bf09-a1f129b8588a/resourceGroups/GLB-GLB-IENO-AIPEAFSIDEVOPS-UAT-RG01
      title: GLB-GLB-IENO-AIPEAFSIDEVOPS-UAT-RG01
  spn: 
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/4b215ac2-2cf7-48c2-ba3b-ef4e5aa02b58/appId/9b57461f-0f6d-467a-b43f-2d4cff654cb5
      title: GLB-DataFactory-4Site-EndUsersManagement-eu-UAT
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/f3a5b964-ac9c-49e8-8ca8-6413314cd609/appId/2417ec81-96e1-4654-a5f6-2594934e39e3
      title: GLB-DATALAB.AZU-AIP. 4SiteGDP.eu-UAT
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/bed6fa8d-a1d2-4ff0-bb2d-26b818862d8a/appId/f0dff35d-c6df-4207-a770-9a4322cfd476
      title: GLB-DATALAB.AZU-AIP. DMYwebappauth.eu-UAT
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/4643c637-be20-4b2c-b2fb-0a00742ba0d5/appId/e007a64f-220b-42c7-ac45-abcea6ed0b5d
      title: GLB-DATALAB.AZU-AIP.DevOpsfsi.eu-UAT
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/ae7a2e1e-2d6d-42fb-a23e-267ee790ca61/appId/405d2fcc-9369-4c37-8a38-90b016484833
      title: GLB-DATALAB.AZU-AIP.expareafsi.eu-UAT
  ad_group:
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/ab7ea034-b7e0-417c-a5c7-f970a7113b7f
      title: SG.CE.FR-AIP_FSI_FR_EXP_UAT
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/dee18f48-472c-476f-a463-9ea091c67902
      title: SG.CE.GLB-ADLS.UAT.EU.4SITE.ADMIN
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/5d8b8235-52c0-4c03-84fd-6b4fac037e05
      title: SG.CE.GLB-ADLS.UAT.EU.4SITE.READER
spec:
  type: infra-environment
  profile:
    displayName: UAT_FSI
  lifecycle: experimental
  subcomponentOf: 4Site
  owner: 4site-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PRD_FSI
  description: Component dedicated to the 4Site PRD Azure environment.
  resource_group:
    - url: https://portal.azure.com/#resource/subscriptions/cf25f2a1-4d40-45af-bb81-87ec46112b3e/resourceGroups/GLB-GLB-IENO-AIPEAFSI-PRD-RG01
      title: GLB-GLB-IENO-AIPEAFSI-PRD-RG01
    - url: https://portal.azure.com/#resource/subscriptions/cf25f2a1-4d40-45af-bb81-87ec46112b3e/resourceGroups/GLB-GLB-IENO-AIPEAFSI-PRD-RG03
      title: GLB-GLB-IENO-AIPEAFSI-PRD-RG03
    - url: https://portal.azure.com/#resource/subscriptions/cf25f2a1-4d40-45af-bb81-87ec46112b3e/resourceGroups/GLB-GLB-IENO-AIPEAFSIDEVOPS-PRD-RG01
      title: GLB-GLB-IENO-AIPEAFSIDEVOPS-PRD-RG01
  spn: 
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/objectId/e1d7089b-afc6-4e3e-9022-9792fcf4aa42/appId/68c5b78e-e4fb-476a-a698-b6bf7cbe7111
      title: GLB-DataFactory-4Site-EndUsersManagement-eu-PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Overview/appId/f91ae54c-c1df-4784-b68a-c6ce02b72278
      title: GLB-DATALAB.AZU-AIP. 4SiteGDP.eu-PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/13ba5c65-b1b9-4331-b504-4e4f050133e8/appId/4eaa3f30-5254-4e86-a50a-70c469dd7756
      title: GLB-DATALAB.AZU-AIP. DMYwebappauth.eu-PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/271623b5-9d88-44a2-85d4-55db129f615c/appId/52b8d838-2360-40eb-a61e-9d57fd4b11d6
      title: GLB-DATALAB.AZU-AIP.DevOpsfsi.eu-PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/ae566a90-aeb9-4d82-adf3-00aff607990d/appId/65dee32e-17b2-428d-b8e9-867beeabb3e1
      title: GLB-DATALAB.AZU-AIP.expareafsi.eu-PRD
  ad_group:
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/30369d66-f8b0-4b1a-90c5-7ce36a83aa11
      title: SG.CE.FR-AIP_FSI_FR_EXP_PRD
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/48eff906-b4c7-42a4-939f-29aa0a6e38e2
      title: SG.CE.FR-AIP_FSI_FR_EXP_PRD_READER
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/b3e03cf4-04cf-4cb0-a61a-0cf54c49254c
      title: SG.CE.GLB-ADLS.PROD.EU.4SITE.ADMIN
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/28564c17-cf91-4065-a11d-341f711013f5
      title: SG.CE.GLB-ADLS.PROD.EU.4SITE.READER
    - url: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/7fbac5b6-6a65-4049-a638-ffaf37ae9e25
      title: SG.CE.GLB-DnD-FORSITEUSERSLIST
spec:
  type: infra-environment
  profile:
    displayName: PRD_FSI
  lifecycle: experimental
  subcomponentOf: 4Site
  owner: 4site-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: 4site-team
  description: 4Site Team
spec:
  type: team
  parent: sodexo
  children: []
  profile:
    displayName: 4Site Team
    email: hamed.ky@sodexo.com
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4-site_4site-integration
  description: Documentation for 4Site integration
  annotations:
    backstage.io/techdocs-ref: dir:default/component/4site/4site_integration/
spec:
  type: documentation
  lifecycle: experimental
  owner: 4site-team
  subcomponentOf: 4Site
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4-site_4site-webapp
  description: Documentation for 4Site webapp
  annotations:
    backstage.io/techdocs-ref: dir:default/component/4site/4site_webapp/
spec:
  type: documentation
  lifecycle: experimental
  owner: 4site-team
  subcomponentOf: 4Site
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 4-site_4site
  description: Documentation for 4Site 
  annotations:
    backstage.io/techdocs-ref: dir:default/component/4site/4site_4site/
spec:
  type: documentation
  lifecycle: experimental
  owner: 4site-team
  subcomponentOf: 4Site