apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-bicep-pipeline
  title: Provisioning resources in SDX Sandbox
  description: Initialize Azure resources to your Resource Group by providing information to this template.
spec:
  owner: aip-team
  type: service

  parameters:
  - title: Azure resources selection
    required:
      - resource_group
      - resource_suffix
      - pattern
    description: "Select the Azure resources you want to deploy using Bicep templates."
    properties:
      resource_group:
          type: string
          description: "Name of the existing Resource Group"
      resource_suffix:
          type: string
          description: "Specify a suffix for naming the instances in your group (must be 6 characters long)"
          minLength: 6
          maxLength: 6
      pattern:
        title: Select a pattern
        type: string
        oneOf:
          - title: Pattern 1 (Azure Databricks + Azure Storage Account + Azure Key Vault + Azure App Insights)
            const: pattern_sandbox_adb
          - title: Pattern 2 (Azure Machine Learning + Azure Storage Account + Azure Key Vault + Azure Container Registry + Azure App Insight)
            const: pattern_sandbox_amls
      extra_resources:
        title: Select extra resources
        type: array
        items:
          type: string
          enum:
            - databricks
            - datafactory
            - datalake
          enumNames:
            - Azure Databricks
            - Azure DataFactory
            - Azure DataLake
        uniqueItems: true
        ui:options:
          widget: checkboxes
      user_login:
        title: Use your login identity
        type: string
        oneOf:
          - title: No, use identity of Backstage to log in for provisioning
            const: "false"
          - title: Yes, use my own identity to log in for provisioning
            const: "true"
      project_repository_url:
          type: string
          description: "Reference your repository url where the infra config files will be pushed (e.g 'https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_DeveloperPlatform/_git/test_dummy_project')"
          default: ""
      branch:
          type: string
          description: "Branch to trigger the pipeline on"
          default: ""

  steps:
    - id: run-azure-pipeline
      name: Trigger Azure DevOps Pipeline
      action: azure:pipeline:run
      input:
        organization: "sdxcloud"
        project: "IST.GLB.GLB.DataFactory_DeveloperPlatform"
        pipelineId: "8986"
        branch: ${{ parameters.branch }}
        pipelineParameters:
          resource_group: ${{ parameters.resource_group }}
          resource_suffix: ${{ parameters.resource_suffix }}
          pattern: ${{ parameters.pattern }}
          extra_resources: ${{ parameters.extra_resources | join(",") }}
          user_login: ${{ parameters.user_login }}
          project_repository_url: ${{ parameters.project_repository_url }}
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-azure-pipeline
  title: Initialize repository with CookieCutter template
  description: Initialize a new repository based on AIP CookieCutter template by providing information to this template.
spec:
  owner: aip-team
  type: service

  parameters:
    - title: Cookiecutter Parameters
      required:
        - author_name
        - author_email
        - project_name
        - project_slug
        - project_short_description
        - project_infra
        - usecase_name
        - version
        - code_license
        - add_notebooks
      properties:
        author_name:
          type: string
          default: "Data Factory"
        author_email:
          type: string
          default: "nicolas.marchand@sodexo.com"
        project_name:
          type: string
          default: "GLB.GLB.DataLab.AIPlatform"
        project_slug:
          type: string
          default: "test_dummy_project"
        project_short_description:
          type: string
          default: "This repository contains all the structure code you need to create a AIP Project compatible with Sodexo Data Factory AI Platform."
        project_infra:
          type: string
          description: "Choose the type of infrastructure this project will target"
          enum: ["adb", "aml", "aml2", "app", "all"]
        usecase_name:
          type: string
          default: "test_dummy_project"
        version:
          type: string
          default: "0.1.0"
        code_license:
          type: string
          enum: ["SODEXO license", "MIT license", "BSD license", "ISC license", "Apache Software License 2.0", "GNU General Public License v3"]
          default: "SODEXO license"
        add_notebooks:
          type: string
          enum: ["y", "n"]
          default: "n"

    - title: Infra Parameters
      required:
        - project_repository_url
        - subscription
        - resource_group
        - user_login
      properties:
        project_repository_url:
          type: string
          description: "A URL of the repository to push CookieCutter output"
        subscription:
          type: string
          description: "Azure Subscription to retrieve resources"
        resource_group:
          type: string
          description: "Azure Resource Group to retrieve resources"
        user_login:
          title: Use your login identity
          type: string
          oneOf:
            - title: No, use identity of Backstage to log in for retrieving resources
              const: "false"
            - title: Yes, use my own identity to log in for retrieving resources
              const: "true"
        branch:
          type: string
          description: "Branch to trigger the pipeline on"
          default: "develop"
        

  steps:
    - id: run-azure-pipeline
      name: Trigger Azure DevOps Pipeline
      action: azure:pipeline:run
      input:
        organization: "sdxcloud"
        project: "GLB.GLB.DataLab.AIPlatform"
        pipelineId: "8853"
        branch: master
        pipelineParameters:
          author_name: ${{ parameters.author_name }}
          author_email: ${{ parameters.author_email }}
          project_name: ${{ parameters.project_name }}
          project_slug: ${{ parameters.project_slug }}
          project_short_description: ${{ parameters.project_short_description }}
          project_infra: ${{ parameters.project_infra }}
          usecase_name: ${{ parameters.usecase_name }}
          version: ${{ parameters.version }}
          code_license: ${{ parameters.code_license }}
          add_notebooks: ${{ parameters.add_notebooks }}
          project_repository_url: ${{ parameters.project_repository_url }}
          subscription: ${{ parameters.subscription }}
          resource_group: ${{ parameters.resource_group }}
          user_login: ${{ parameters.user_login }}