apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AI-Platform
  description: AI Platform project is a made to help deliver complex data projects in a quick, secure and standardised way while being compliant with Sodexo policies in terms of security and infrastructure.
  links:
    - url: https://sdxcloud.visualstudio.com/GLB.GLB.DataLab.AIPlatform/_workitems
      title: Azure DevOps Board
spec:
  type: usecase
  profile:
    displayName: AI-Platform
  lifecycle: experimental
  owner: aip-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GLB.GLB.DataLab.AIPlatform.Cookiecutter
  description: This repository contains all the structure code you need to create a AIP Project compatible with Sodexo Data Factory AI Platform.
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/GLB.GLB.DataLab.AIPlatform/_git/GLB.GLB.DataLab.AIPlatform.Cookiecutter
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: GLB.GLB.DataLab.AIPlatform/GLB.GLB.DataLab.AIPlatform.Cookiecutter
    aip.check: aip/cookiecutter/aip_check.html
spec:
  type: repo
  owner: aip-team
  subcomponentOf: AI-Platform
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GLB.GLB.DataLab.AIPlatform.CLI
  description: AIPCLI is a utility providing a command line interface to interact with AI Platform environments and assets.
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/GLB.GLB.DataLab.AIPlatform/_git/GLB.GLB.DataLab.AIPlatform.CLI
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: GLB.GLB.DataLab.AIPlatform/GLB.GLB.DataLab.AIPlatform.CLI
    sonarqube.org/project-key: sodexoSonarqube/GLB.GLB.DataLab.AIPlatform_GLB.GLB.DataLab.AIPlatform.CLI_AZZeC7NIZNnaRRY8khp8
  links:
    - url: https://aip.datalab.sodexo.com/aip/docs/cli
      title: CLI documentation
spec:
  type: repo
  owner: aip-team
  subcomponentOf: AI-Platform
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: GLB.GLB.DataLab.AIPlatform.SDK
  description: AIPSDK is a Python library providing a set of classes and methods to interact with AI Platform environments and assets from any Python project.
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/GLB.GLB.DataLab.AIPlatform/_git/GLB.GLB.DataLab.AIPlatform.SDK
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: GLB.GLB.DataLab.AIPlatform/GLB.GLB.DataLab.AIPlatform.SDK
    sonarqube.org/project-key: sodexoSonarqube/GLB.GLB.DataLab.AIPlatform_GLB.GLB.DataLab.AIPlatform.SDK_AZXxa6KVZNnaRRY8khLc
    trivy.security-report: aip/sdk/trivy_report.html
    
  links:
    - url: https://aip.datalab.sodexo.com/aip/docs/sdk
      title: SDK documentation
spec:
  type: repo
  owner: aip-team
  subcomponentOf: AI-Platform
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SANDBOX_AIP
  description: Component dedicated to the SANDBOX Azure environment.
  resource_group:
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: IST-GLB-IENO-AIPWE-BOX-RG01
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: GRP-EU-AIP-DEV-RG10
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: GLB-GLB-IENO-AIPSAWEB-PRD-RG01
  spn: 
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: GLB-DATALAB.AZU-AIP.SHAREDAIP.eu-DEV
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: GLB-DATALAB.AZU-AIP.SHAREDAIP.eu-UAT
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: GLB-DATALAB.AZU-AIP.SHAREDAIP.eu-PRD
  ad_group:
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/fea1e9f0-0e20-426f-906e-bc76e5a566ad/resourceGroups/IST-GLB-IENO-AIPWE-BOX-RG01/overview
      title: My-AD-Group
spec:
  type: infra-environment
  profile:
    displayName: SANDBOX_AIP
  lifecycle: experimental
  subcomponentOf: AI-Platform
  owner: aip-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DEV_AIP
  description: Component dedicated to the DEV Azure environment.
spec:
  type: infra-environment
  profile:
    displayName: DEV_AIP
  lifecycle: experimental
  subcomponentOf: AI-Platform
  owner: aip-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: aip-team
  description: AIPlatform Team
spec:
  type: team
  parent: sodexo
  children: []
  profile:
    displayName: AI-Platform Team
    email: hamed.ky@sodexo.com
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hamed.ky
spec:
  profile:
    displayName: Hamed Ky
    email: hamed.ky@sodexo.com
  memberOf: [aip-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: maeliza.seymour
spec:
  profile:
    displayName: Maeliza Seymour
    email: maeliza.seymour@sodexo.com
  memberOf: [aip-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: christophe.gougam.ext
spec:
  profile:
    displayName: Christophe Gougam
    email: christophe.gougam.ext@sodexo.com
  memberOf: [aip-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: samuel.rochette
spec:
  profile:
    displayName: Samuel Rochette
    email: samuel.rochette@sodexo.com
  memberOf: [aip-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: maxime.guiblin.ext
spec:
  profile:
    displayName: Maxime Guiblin
    email: maxime.guiblin.ext@sodexo.com
  memberOf: [aip-team]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aip_sdk
  description: Documentation for the AIP SDK source code
  annotations:
    backstage.io/techdocs-ref: dir:default/component/aip/aip_sdk/
spec:
  type: documentation
  lifecycle: experimental
  owner: aip-team
  subcomponentOf: GLB.GLB.DataLab.AIPlatform.SDK
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aip_cli
  description: Documentation for the AIP CLI source code
  annotations:
    backstage.io/techdocs-ref: dir:default/component/aip/aip_cli/
spec:
  type: documentation
  lifecycle: experimental
  owner: aip-team
  subcomponentOf: GLB.GLB.DataLab.AIPlatform.CLI
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aip_aip-manuals
  description: Documentation for the AIP
  annotations:
    backstage.io/techdocs-ref: dir:default/component/aip/aip_AI Platform Documentation/
spec:
  type: documentation
  lifecycle: experimental
  owner: aip-team
  subcomponentOf: AI-Platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aip_wiki
  description: AIP Wiki
  annotations:
    backstage.io/techdocs-ref: dir:default/component/aip/aip_wiki/
spec:
  type: documentation
  lifecycle: experimental
  owner: aip-team
  subcomponentOf: AI-Platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-guide
  description: Sodexo Developer Portal's User Guide
  annotations:
    backstage.io/techdocs-ref: dir:default/component/user-guide/
spec:
  type: documentation
  lifecycle: experimental
  owner: aip-team
  subcomponentOf: AI-Platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-guide-test
  description: Sodexo Developer Portal's User Guide Test
  annotations:
    backstage.io/techdocs-ref: dir:default/component/user-guide-test/
spec:
  type: documentation
  lifecycle: experimental
  owner: aip-team
  subcomponentOf: AI-Platform