apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PAG
  description: PAG Description
spec:
  type: usecase
  profile:
    displayName: PAG
  lifecycle: experimental
  owner: pag-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pag-team
  description: PAG Team
spec:
  type: team
  parent: sodexo
  children: []
  profile:
    displayName: PAG Team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pag_pag
  title: OptiMenu
  description: Documentation for OptiMenu
  annotations:
    backstage.io/techdocs-ref: dir:default/component/pag_pag
spec:
  type: documentation
  lifecycle: experimental
  owner: pag-team
  subcomponentOf: PAG