apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ProductSwap
  description: AI Platform project is a made to help deliver complex data projects in a quick, secure and standardised way while being compliant with Sodexo policies in terms of security and infrastructure.
  links:
    - url: https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_ProductSwap/_workitems/recentlyupdated/
      title: Azure DevOps Board
spec:
  type: usecase
  profile:
    displayName: ProductSwap
  lifecycle: experimental
  owner: productswap-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IST.GLB.GLB.DataFactory_ProductSwap.AMLS.Main
  description: Description of the AMLS Main repository for ProductSwap
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_ProductSwap/_git/IST.GLB.GLB.DataFactory_ProductSwap.AMLS.Main
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: IST.GLB.GLB.DataFactory_ProductSwap/IST.GLB.GLB.DataFactory_ProductSwap.AMLS.Main
spec:
  type: repo
  owner: productswap-team
  subcomponentOf: ProductSwap
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: IST.GLB.GLB.DataFactory_ProductSwap.Monorepo
  description: Description of the Monorepo project for ProductSwap
  annotations:
    backstage.io/source-location: url:https://sdxcloud.visualstudio.com/IST.GLB.GLB.DataFactory_ProductSwap/_git/IST.GLB.GLB.DataFactory_ProductSwap.Monorepo
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: IST.GLB.GLB.DataFactory_ProductSwap/IST.GLB.GLB.DataFactory_ProductSwap.Monorepo
spec:
  type: repo
  owner: productswap-team
  subcomponentOf: ProductSwap
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DEV_PSW
  description: Component dedicated to the SANDBOX Azure environment.
  resource_group:
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/746ac5b9-70eb-4c76-bdf4-0664bfdff2ea/resourceGroups/GRP-EU-AIP-DEV-RG07/overview
      title: GRP-EU-AIP-DEV-RG07
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAPSW-DEV-RG01/overview
      title: GLB-GLB-IENO-AIPEAPSW-DEV-RG01
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAPSW-DEV-RG02/overview
      title: GLB-GLB-IENO-AIPEAPSW-DEV-RG02
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/c0978b9d-b809-45f4-aa76-391ceb2cfdba/resourceGroups/GLB-GLB-IENO-AIPEAPSW-DEV-RG03/overview
      title: GLB-GLB-IENO-AIPEAPSW-DEV-RG03
  spn: 
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/84cb0035-3a6d-420f-ab12-f5dde74feb08/appId/f551df7e-a7f1-4261-a355-4f8d35b831dc
      title: GLB-DATALAB.AZU-AIP.expareapswuk.eu-DEV
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/7a404c0e-6745-4de9-8d18-7cd327b4fbd7/appId/94e460ad-f9bb-41ce-a272-71af66f52702
      title: GLB-DATALAB.AZU-AIP.DevopsPSW.eu-DEV
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/b85a4d94-13a4-45aa-9f9a-6888ce645cd2/appId/0c4b36fc-1b2d-4ddc-8463-20a1411e60f6
      title: GLB-DATALAB.AZU-AIP.PSWwebappauthSDX.eu-DEV
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/ad0db57c-41d4-4e1e-96ee-6993a8c95f44/appId/6add052b-c8fc-4b5a-80dc-3395ba8dc8ce
      title: GLB-DATALAB.AZU-AIP.SHAREDAIP.eu-DEV
  ad_group:
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupDetailsMenuBlade/Overview/groupId/6e386382-7782-4142-bd00-b4dbf77d2c59
      title: SG.CE.FR-AIP_PSW_UK_EXP_DEV
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupDetailsMenuBlade/Overview/groupId/7b5a7645-703d-45eb-a946-e21b99bae213
      title: SG.CE.GLB-ADLS.DEV.EU.PSW.ADMIN
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupDetailsMenuBlade/Overview/groupId/af004e9b-4ea4-4e64-8ea9-0077c7e07f9d
      title: SG.CE.GLB-ADLS.DEV.EU.PSW.READER
spec:
  type: infra-environment
  profile:
    displayName: DEV_PSW
  lifecycle: experimental
  subcomponentOf: ProductSwap
  owner: productswap-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PRD_PSW
  description: Component dedicated to the SANDBOX Azure environment.
  resource_group:
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/cf25f2a1-4d40-45af-bb81-87ec46112b3e/resourceGroups/GLB-GLB-IENO-AIPEAPSW-PRD-RG01/overview
      title: GLB-GLB-IENO-AIPEAPSW-PRD-RG01
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/cf25f2a1-4d40-45af-bb81-87ec46112b3e/resourceGroups/GLB-GLB-IENO-AIPEAPSW-PRD-RG02/overview
      title: GLB-GLB-IENO-AIPEAPSW-PRD-RG02
    - url: https://portal.azure.com/#@sodexo.onmicrosoft.com/resource/subscriptions/cf25f2a1-4d40-45af-bb81-87ec46112b3e/resourceGroups/GLB-GLB-IENO-AIPEAPSW-PRD-RG03/overview
      title: GLB-GLB-IENO-AIPEAPSW-PRD-RG03
  spn: 
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/604b029b-5f0c-4c52-9d10-b1b5acb5da32/appId/ad5f3b98-1ca1-4121-9b9e-3536378a8d16
      title: GLB-DATALAB.AZU-AIP. PSWwebappauthSDX.eu-PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/3b67f761-fef8-4e56-afab-d05e962e3b19/appId/aa776ee9-62b5-4cdc-8b8f-5a87e764d502
      title: GLB-DATALAB.AZU-AIP.DevopsPSW.eu-PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ManagedAppMenuBlade/Overview/objectId/e3b5b6ec-85d1-4ecc-bf9c-ff4e4ea1f7f7/appId/3f86f071-267f-44c2-bdb0-e96ac831e138
      title: GLB-DATALAB.AZU-AIP.expareapswuk.eu-PRD
  ad_group:
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupDetailsMenuBlade/Overview/groupId/8623bd40-fa79-487c-adf4-b26a4e43ae5a
      title: SG.CE.FR-AIP_PSW_UK_EXP_PRD
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupDetailsMenuBlade/Overview/groupId/7be46871-f807-469a-939d-67257f575e32
      title: SG.CE.GLB-ADLS.PRD.EU.PSW.ADMIN
    - url: https://portal.azure.com/#blade/Microsoft_AAD_IAM/GroupDetailsMenuBlade/Overview/groupId/8ec02075-cf31-472c-82f7-1dacbf954d5f
      title: SG.CE.GLB-ADLS.PRD.EU.PSW.READER
spec:
  type: infra-environment
  profile:
    displayName: PRD_PSW
  lifecycle: experimental
  subcomponentOf: ProductSwap
  owner: productswap-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: productswap-team
  description: ProductSwap Team
spec:
  type: team
  parent: sodexo
  children: []
  profile:
    displayName: ProductSwap Team
    email: hamed.ky@sodexo.com
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-swap_config
  description: Documentation for the ProductSwap config
  annotations:
    backstage.io/techdocs-ref: dir:default/component/product-swap/product-swap_config/
spec:
  type: documentation
  lifecycle: experimental
  owner: productswap-team
  subcomponentOf: ProductSwap
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-swap_python
  description: Documentation for the ProductSwap python
  annotations:
    backstage.io/techdocs-ref: dir:default/component/product-swap/product-swap_python/
spec:
  type: documentation
  lifecycle: experimental
  owner: productswap-team
  subcomponentOf: ProductSwap
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-swap_technical
  description: Documentation for the ProductSwap technical
  annotations:
    backstage.io/techdocs-ref: dir:default/component/product-swap/product-swap_technical/
spec:
  type: documentation
  lifecycle: experimental
  owner: productswap-team
  subcomponentOf: ProductSwap
