####################
# Copyright © 2020 Sodexo. All rights reserved.
# Author(s): hamed.ky@sodexo.com
####################

variables:
  artifactFeeds: AIP-feed
  serviceConnectionSandbox: Srv_Cnx_AIP_SANDBOX
  serviceConnectionSdxDev: GLB-SDP-DEVOPS-CICD-D

trigger:
- main
- develop

jobs:
  - job: ValidateSourceBranch
    displayName: Validate Source Branch
    steps:
      - script: |
          if [[ "$(System.PullRequest.TargetBranch)" == "refs/heads/main" ]] && [[ "$(System.PullRequest.SourceBranch)" != "refs/heads/develop" ]];
          then
            echo "Pull requests to 'main' are only allowed from 'develop'."
            exit 1
          else
            echo "Validation of source branch success"
          fi
        displayName: Check PR target branch for main


  - job: TestAndBuild
    pool:
      vmImage: ubuntu-latest
    container:
      image: aziecr1aip001.azurecr.io/aip_devcontainer
      endpoint: SDXSandbox_Docker_Registry
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: Install Node.js

      - bash: |
          corepack enable
          corepack prepare yarn@stable --activate
        displayName: Enable Yarn

      - bash: |
          set -e
          cd src/backstage
          yarn install --frozen-lockfile
          yarn lint:all
        displayName: Run ESLint checks


  # - job: Doc
  #   displayName: Build and Push Documentation
  #   dependsOn: TestAndBuild
  #   pool:
  #     vmImage: ubuntu-latest
  #   container:
  #     image: aziecr1aip001.azurecr.io/aip_devcontainer
  #     endpoint: SDXSandbox_Docker_Registry
  #   steps:
  #     - task: PipAuthenticate@1
  #       inputs:
  #         artifactFeeds: $(artifactFeeds)
  #         onlyAddExtraIndex: true
  #       displayName: Pip authentication

  #     - script: |
  #         echo "Current branch is $(Build.SourceBranch)"
  #         if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
  #           VERSION='latest'
  #         elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
  #           VERSION='merge'
  #         else
  #           VERSION='tmp'
  #         fi
  #         PATHDOC=docs/build/html/
  #         echo "##vso[task.setvariable variable=VERSION]$VERSION"
  #         echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
  #         echo "Found VERSION=$VERSION"
  #         echo "Found PATHDOC=$PATHDOC"
  #       displayName: Get doc version

  #     - script: |
  #         set -e
  #         export PATH="$HOME/.local/bin:$PATH"
  #         if [[ -d backstage ]]; then cd backstage ; fi
  #         aip core docs build --add_markdowns --install_packages
  #         if [[ ! -d $(PATHDOC) ]];
  #         then
  #           echo "Not found generated doc at path $(PATHDOC)"
  #           exit 1
  #         fi
  #       displayName: Build doc

  #     - task: AzureCLI@2
  #       inputs:
  #         azureSubscription: $(serviceConnectionSandbox)
  #         scriptType: bash
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           if [[ -d backstage ]]; then cd backstage ; fi
  #           aip core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
  #       displayName: Push doc


  - job: DeploySandbox
    displayName: Deploy to SDX Sandbox
    dependsOn: TestAndBuild
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
            eq(variables['deploy_sandbox'], 'true')
        )
      )
    pool:
      vmImage: ubuntu-latest
    container:
      image: aziecr1aip001.azurecr.io/aip_devcontainer
      endpoint: SDXSandbox_Docker_Registry
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Start deploying backstage..."
            aip app container deploy --all
        displayName: Deploy backstage app


  - job: BuildForSdxDev
    dependsOn: TestAndBuild
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            eq(variables['deploy_sdxdev'], 'true')
        )
      )
    pool:
      vmImage: ubuntu-24.04
    container:
      image: aziecr1aip001.azurecr.io/aip_devcontainer
      endpoint: SDXSandbox_Docker_Registry
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

      - bash: |
          set -e
          echo "Build backstage..."
          aip -i SDXDEV app container build --container_name backstage_app
        displayName: Build docker images on default microsoft agent (with internet connection)

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login --name aziecr1aip001
            echo "Push backstage..."
            docker tag aziecr1exu749.azurecr.io/backstage_app:latest aziecr1aip001.azurecr.io/backstage_app:latest
            docker push aziecr1aip001.azurecr.io/backstage_app:latest
        displayName: Tag and push images to Sandbox container registry


  - job: DeploySdxDev
    dependsOn: BuildForSdxDev
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            eq(variables['deploy_sdxdev'], 'true')
        )
      )
    pool:
      name: DevOps agent pool NON-PROD CICD - SDP
    container:
      image: aziecr1aip001.azurecr.io/aip_devcontainer
      endpoint: SDXSandbox_Docker_Registry
    steps:

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login -n aziecr1aip001
            docker pull aziecr1aip001.azurecr.io/backstage_app:latest
        displayName: Pull images from Sandbox container registry to custom DevOps agent (with SDX DEV access)

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSdxDev)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login -n aziecr1exu749
            echo "Push backstage backend..."
            docker tag aziecr1aip001.azurecr.io/backstage_app:latest aziecr1exu749.azurecr.io/backstage_app:latest
            aip -i SDXDEV app container push --container_name backstage_app
        displayName: Tag and push imags to SDXDEV container registry

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSdxDev)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Start deploying backstage..."
            aip -i SDXDEV app container deploy --all --deploy_only
        displayName: Deploy backstage app


  - job: BuildAndPublishTechDocs
    displayName: Build and Publish TechDocs
    dependsOn: TestAndBuild
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            eq(variables['Build.SourceBranch'], 'refs/heads/develop')
        )
      )
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

      - script: |
          echo "Installing TechDocs CLI..."
          npm install -g @techdocs/cli
          echo "TechDocs CLI installed successfully"
        displayName: Install TechDocs CLI

      - script: |
          echo "Generating TechDocs documentation..."
          cd docs/user-guide
          npx @techdocs/cli generate --source-dir . --output-dir ./techdocs-user-guide --verbose
          if [[ ! -d ./techdocs-user-guide ]];
          then
            echo "TechDocs build directory not found"
            exit 1
          fi
          echo "TechDocs generated successfully"
        displayName: Generate TechDocs

      - task: AzureCLI@2
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Publishing TechDocs to Azure Blob Storage on Sandbox..."
            aip core docs push --account_name aziest1doc001 --datastore documentation --path_in_datastore default/component/user-guide/ --path_local docs/techdocs-user-guide/
            echo "TechDocs published successfully to Sandbox"
        displayName: Publish TechDocs to Azure Blob Storage on Sandbox

      - task: AzureCLI@2
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
        inputs:
          azureSubscription: $(serviceConnectionSdxDev)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Publishing TechDocs to Azure Blob Storage on DEV..."
            aip core docs push --account_name aziest1fuc810 --datastore documentation --path_in_datastore default/component/user-guide/ --path_local docs/techdocs-user-guide/
            echo "TechDocs published successfully to DEV"
        displayName: Publish TechDocs to Azure Blob Storage on SDX DEV
