####################
# Copyright © 2020 Sodexo. All rights reserved.
# Author(s): hamed.ky@sodexo.com
####################

variables:
  artifactFeeds: AIP-feed
  PythonDownloadServiceConnections: AIPFeed_PythonPackageDownload
  serviceConnectionSandbox: Srv_Cnx_AIP_SANDBOX
  serviceConnectionSdxDev: GLB-SDP-DEVOPS-CICD-D

trigger:
- main
- develop


jobs:
  - job: ValidateSourceBranch
    displayName: Validate Source Branch
    steps:
      - script: |
          if [[ "$(System.PullRequest.TargetBranch)" == "refs/heads/main" ]] && [[ "$(System.PullRequest.SourceBranch)" != "refs/heads/develop" ]];
          then
            echo "Pull requests to 'main' are only allowed from 'develop'."
            exit 1
          else
            echo "Validation of source branch success"
          fi
        displayName: Check PR target branch for main


  - job: TestAndBuild
    pool:
      vmImage: ubuntu-latest
    container:
      image: aziecr1fpt999.azurecr.io/aip_devcontainer:backstage
      endpoint: SrvCnx_AIP_Docker_Registry
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

#      - bash: |
#          set -e
#          echo "Run ESLint checks"
#          cd src/backstage
#          yarn install
#          yarn lint:all
#          if [ "$?" != 0 ]; then
#              echo "Exiting with failure because ESLint found issues";
#              exit 1;
#          fi
#        displayName: Run code formatting checks

      - bash: |
          coverage run --source=src -m pytest tests/** --capture=no --show-capture=no --doctest-modules --junitxml=junit/test-results.xml
        displayName: Run tests with coverage

      - bash: |
          set -e
          echo "Build backstage backend..."
          aip app container build --container_name backstage_app_back
          echo "Build backstage frontend..."
          aip app container build --container_name backstage_app_front
        displayName: Build docker images


#  - job: Doc
#    displayName: Build and Push Documentation
#    dependsOn: TestAndBuild
#    pool:
#      vmImage: ubuntu-latest
#    container:
#      image: aziecr1fpt999.azurecr.io/aip_devcontainer:backstage
#      endpoint: SrvCnx_AIP_Docker_Registry
#    steps:
#      - script: |
#          echo "Current branch is $(Build.SourceBranch)"
#          if [[ $(Build.SourceBranch) == "refs/heads/main" ]]; then
#            VERSION='latest'
#          elif [[ $(Build.SourceBranch) == "refs/heads/develop" ]]; then
#            VERSION='merge'
#          else
#            VERSION='tmp'
#          fi
#          PATHDOC=docs/build/html/
#          echo "##vso[task.setvariable variable=VERSION]$VERSION"
#          echo "##vso[task.setvariable variable=PATHDOC]$PATHDOC"
#          echo "Found VERSION=$VERSION"
#          echo "Found PATHDOC=$PATHDOC"
#        displayName: Get doc version
#
#      - script: |
#          if [[ -d backstage ]]; then cd backstage ; fi
#          aip core docs build --add_markdowns --install_packages
#          if [[ ! -d $(PATHDOC) ]];
#          then
#            echo "Not found generated doc at path $(PATHDOC)"
#            exit 1
#          fi
#        displayName: Build doc
#
#      - task: AzureCLI@2
#        inputs:
#          azureSubscription: $(serviceConnectionSandbox)
#          scriptType: bash
#          scriptLocation: inlineScript
#          inlineScript: |
#            if [[ -d backstage ]]; then cd backstage ; fi
#            aip core docs push --path_local $(PATHDOC) --account_name aziest1doc001 --datastore documentation --path_in_datastore backstage/$(VERSION)/ --credential Docs-StorageAccount-Key --overwrite true
#        displayName: Push doc


  - job: DeploySandbox
    displayName: Deploy to SDX Sandbox
    dependsOn: TestAndBuild
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
            eq(variables['deploy_sandbox'], 'true')
        )
      )
    pool:
      vmImage: ubuntu-latest
    container:
      image: aziecr1fpt999.azurecr.io/aip_devcontainer:backstage
      endpoint: SrvCnx_AIP_Docker_Registry
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Start deploying backstage..."
            aip app container deploy --all
        displayName: Deploy backstage app


  - job: BuildForSdxDev
    dependsOn: TestAndBuild
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            eq(variables['deploy_sdxdev'], 'true')
        )
      )
    pool:
      vmImage: ubuntu-latest
    container:
      image: aziecr1fpt999.azurecr.io/aip_devcontainer:backstage
      endpoint: SrvCnx_AIP_Docker_Registry
    steps:
      - task: PipAuthenticate@1
        inputs:
          artifactFeeds: $(artifactFeeds)
          onlyAddExtraIndex: true
        displayName: Pip authentication

      - bash: |
          set -e
          echo "Build backstage backend..."
          aip -i SDXDEV app container build --container_name backstage_app_back
          echo "Build backstage frontend..."
          aip -i SDXDEV app container build --container_name backstage_app_front
        displayName: Build docker images on default microsoft agent (with internet connection)

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login --name aziecr1aip001
            echo "Push backstage backend..."
            docker tag aziecr1exu749.azurecr.io/backstage_app_back:latest aziecr1aip001.azurecr.io/backstage_app_back:latest
            docker push aziecr1aip001.azurecr.io/backstage_app_back:latest
            echo "Push backstage frontend..."
            docker tag aziecr1exu749.azurecr.io/backstage_app_front:latest aziecr1aip001.azurecr.io/backstage_app_front:latest
            docker push aziecr1aip001.azurecr.io/backstage_app_front:latest
        displayName: Tag and push images to Sandbox container registry


  - job: DeploySdxDev
    dependsOn: BuildForSdxDev
    condition: and(
        succeeded(),
        or(
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            eq(variables['deploy_sdxdev'], 'true')
        )
      )
    pool:
      name: DevOps agent pool NON-PROD CICD - SDP
    container:
      image: aziecr1fpt999.azurecr.io/aip_devcontainer:backstage
      endpoint: SrvCnx_AIP_Docker_Registry
    steps:

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSandbox)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login -n aziecr1aip001
            docker pull aziecr1aip001.azurecr.io/backstage_app_back:latest
            docker pull aziecr1aip001.azurecr.io/backstage_app_front:latest
        displayName: Pull images from Sandbox container registry to custom DevOps agent (with SDX DEV access)

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSdxDev)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az acr login -n aziecr1exu749
            echo "Push backstage backend..."
            docker tag aziecr1aip001.azurecr.io/backstage_app_back:latest aziecr1exu749.azurecr.io/backstage_app_back:latest
            aip -i SDXDEV app container push --container_name backstage_app_back
            echo "Push backstage frontend..."
            docker tag aziecr1aip001.azurecr.io/backstage_app_front:latest aziecr1exu749.azurecr.io/backstage_app_front:latest
            aip -i SDXDEV app container push --container_name backstage_app_front
        displayName: Tag and push imags to SDXDEV container registry

      - task: AzureCLI@2
        inputs:
          azureSubscription: $(serviceConnectionSdxDev)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            echo "Start deploying backstage..."
            aip -i SDXDEV app container deploy --all --deploy_only
        displayName: Deploy backstage app
