site_name: AIP SDK Documentation
site_description: Documentation for the AI Platform SDK
site_author: AIP Team
site_url: https://aip.datalab.sodexo.com/aip/docs/sdk

repo_name: GLB.GLB.DataLab.AIPlatform.SDK
repo_url: https://sdxcloud.visualstudio.com/GLB.GLB.DataLab.AIPlatform/_git/GLB.GLB.DataLab.AIPlatform.SDK

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo

# plugins:
#   - techdocs-core

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api-reference.md 