apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: post-deployment-config
  title: Post-Deployment Infra Parameters Configuration
  description: Run post-deployment script to configure App Insights, Storage, and ACR secrets in the Key Vault.
spec:
  owner: team-sdx
  type: service

  parameters:
    - title: Post-Deployment Infra Parameters Configuration
      required:
        - resourceGroupName
        - keyVaultName
        - appInsightsName
        - storageAccountName
        - acrName
      properties:
        resourceGroupName:
          type: string
          title: Resource Group Name
          description: Name of the Azure Resource Group containing the resources.
        keyVaultName:
          type: string
          title: Key Vault Name
          description: Name of the Azure Key Vault to store secrets.
        appInsightsName:
          type: string
          title: App Insights Name
          description: Name of the Application Insights resource.
        storageAccountName:
          type: string
          title: Storage Account Name
          description: Name of the Azure Storage Account.
        acrName:
          type: string
          title: ACR Name
          description: Name of the Azure Container Registry.
        logAnalyticsName:
          type: string
          title: Log Analytics Name
          description: Name of the Azure Log Analytics resource.
        user_login:
          title: Use your login identity
          type: string
          oneOf:
            - title: Yes, use my own identity to log in for retrieving resources
              const: "true"
            - title: No, use identity of Backstage to log in for retrieving resources
              const: "false"
  
  steps:
    - id: run-azure-pipeline
      name: Trigger Azure DevOps Pipeline
      action: azure:pipeline:run
      input:
        organization: "sdxcloud"
        project: "IST.GLB.GLB.DataFactory_DeveloperPlatform"
        pipelineId: "9917"
        branch: "main"
        pipelineParameters:
          resource_group_name: ${{ parameters.resourceGroupName }}
          keyvault_name: ${{ parameters.keyVaultName }}
          appinsights_name: ${{ parameters.appInsightsName }}
          storage_account_name: ${{ parameters.storageAccountName }}
          acr_name: ${{ parameters.acrName }}
          log_analytics_name: ${{ parameters.logAnalyticsName }}
          user_login: ${{ parameters.user_login }}

