app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  listen:
    port: 3000
    # Uncomment the following host directive to bind to specific interfaces
    host: 0.0.0.0

azureDevOps:
  host: dev.azure.com
  organization: sdxcloud
  token: ${BACKSTAGE_ACCESS_TOKEN}

sonarqube:
  instances:
    - name: sodexoSonarqube
      instanceKey: sodexoSonarqube
      baseUrl: https://scrutineer.sodexonet.com
      apiKey: ${BACKSTAGE_SONARQUBE_TOKEN}

organization:
  name: My Company

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: better-sqlite3
    connection: ':memory:'
  proxy:
    endpoints:
      # This is an example of how to set up a proxy endpoint for Azure DevOps
      # The path is prefixed with /proxy/azure-devops, so the full URL would be
      # http://localhost:7007/proxy/azure-devops/{organization}/{project}/_apis/pipelines/{pipelineId}/runs
      '/proxy/azure-devops':
        target: https://dev.azure.com
        changeOrigin: true
        # Remove the proxy path when forwarding the request
        pathRewrite:
          '^/proxy/azure-devops': ''
        # Format authorization header according to Azure DevOps API requirements
        headers:
          Authorization: ${{ 'Basic ' + Buffer.from(':' + env.BACKSTAGE_ACCESS_TOKEN).toString('base64') }}
        # Allow headers to pass through
        allowedHeaders: ['Authorization', 'Content-Type']
  reading:
    allow:
      - host: aziest1doc001.blob.core.windows.net
      - host: sdxcloud.visualstudio.com
      - host: dev.azure.com

integrations:
  azure:
    - host: dev.azure.com #sdxcloud.visualstudio.com
      credentials:
        - personalAccessToken: ${BACKSTAGE_ACCESS_TOKEN}
        # - clientId: ${BACKSTAGE_CLIENT_ID}
        #   clientSecret: ${BACKSTAGE_CLIENT_SECRET}
        #   tenantId: ${BACKSTAGE_TENANT_ID}
  azureDevOps:
    - host: dev.azure.com
      organization: sdxcloud
      token: ${BACKSTAGE_ACCESS_TOKEN}

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'docker'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: 'documentation'
      credentials:
        accountName: aziest1doc001
        accountKey: 295PqTgCec9cXl3eyKHG5hFg1lNLAh+laku6ZvbJvkQEEv79bGolTNCtSkbzcTJaSHZLvjSI4fih+AStxTnyRw==
      # Optional: Set the path prefix where your documentation is stored
      path: 'backstage/tmp'
  # Disable search indexing for now to avoid the search index error
  search:
    enabled: false

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    guest: {}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    # Sodexo data
    - type: file
      target: ../../sodexo/all.yaml
      rules:
        - allow: [User, Group, Component, System, API, Resource, Location]

    # VM template
    - type: file
      target: ../../sodexo/templates/azure-vm-template.yaml
      rules:
        - allow: [Template]

    # Patterns template
    - type: file
      target: ../../sodexo/templates/azure-patterns-template.yaml
      rules:
        - allow: [Template]

    # AIP templates
    - type: file
      target: ../../sodexo/aip-template.yaml
      rules:
        - allow: [Template] 

    # AIP catalog
    - type: file
      target: ../../sodexo/aip-catalog.yaml
      rules:
        - allow: [User, Group, Component, System, API, Resource, Location]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]

  providers:
    azureDevOps:
      sdxcloudBackstageCatalogProvider: # identifies your dataset / provider independent of config changes
        organization: sdxcloud
        project: 'IST.GLB.GLB.DataFactory_DeveloperPlatform'
        repository: '*'
        path: /**/catalog-info.yaml
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 3 }

kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

qeta:
  permission:
    enabled: false
  authentication:
    required: false