app:
  baseUrl: ${FRONT_ENDPOINT}

backend:
  baseUrl: ${BACK_ENDPOINT}

  cors:
    origin: ${CORS_ENDPOINT}

  database:
    client: pg
    connection:
      host: ${PG_HOST}
      port: ${PG_PORT}
      database: ${PG_DATABASE}
      user: ${PG_USER}
      password: ${PG_PASSWORD}
      ssl:
        rejectUnauthorized: false
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt


