apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    dev.azure.com/sdxcloud: sdxcloud/GLB.GLB.DataLab.AIPlatform/GLB.GLB.DataLab.AIPlatform.Manuals
metadata:
  name: backstage-plugin-azure-devops
  title: '@backstage-community/plugin-azure-devops'
spec:
  lifecycle: experimental
  type: backstage-frontend-plugin
  owner: awanlin
spec:
  type: service
