apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    dev.azure.com/host-org: dev.azure.com/sdxcloud
    dev.azure.com/project-repo: IST.GLB.GLB.DataFactory_DeveloperPlatform/IST.GLB.GLB.DataFactory_DeveloperPlatform.Backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
