apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-repo-template
  title: Azure Repo Template
  description: A form to configure Azure DevOps repo info
spec:
  type: template
  lifecycle: experimental
  owner: data-team
